# Number of events per square degree in OGLE and LSST catalogs

### User

In [1]:
# USER

DirSaveOutput = '/Users/arturo/Dropbox/Research/Articulos/\
14_PLASTICC/OGLE/Plots/'

# -------------------------------
# Given that javascript doesn't work in JupyterLab, I have to set the 
# name of the notebook by hand
NotebookName = 'OGLE_data.ipynb'

### Automatic

In [2]:
import numpy as np
# import pandas as pd
import os # To use command line like instructions
import glob # To read the files in my directory
from matplotlib import pyplot as plt

5+4

9

In [3]:
# Get the current date and time
import datetime 

# Read the time and date now
now = datetime.datetime.now()
print now

2018-07-12 17:47:07.324217


In [4]:
#     Patch of the sky in the Milky way observed by OGLE:

ra_min = 250.0; ra_max = 283.0;
dec_min = -40.0; dec_max = -15.0;

------------

# Section 1
# OGLE

In [ ]:
# Read OGLE data table

OGLE_file = 'tl.txt'
Dir_OGLE_file = '/Users/arturo/Documents/Research/LSST/OGLE/'

OGLE_ra_dec_data = np.genfromtxt(Dir_OGLE_file+OGLE_file, usecols=[9,10])

In [ ]:
"""
array([[ 271.0843875 ,  -27.41257778],
       [ 271.08435833,  -27.41314444],
       [ 271.22726667,  -27.43056111],
       [ 271.22724583,  -27.4305    ],
       [ 271.41127917,  -27.14167778]])
"""

OGLE_ra_dec_data[:5]

In [ ]:
print "# %s"%OGLE_ra_dec_data[0]
print "# %s"%OGLE_ra_dec_data[-1]

# [ 271.0843875   -27.41257778]
# [ 265.295125    -27.58233333]

In [ ]:
print "# %s lensing events in OGLE catalog"%len(OGLE_ra_dec_data)
print "#  Find min, max values of (ra, dec):"
print "# %.4f < ra < %.4f  | %.4f < dec < %.4f"%(
    min(OGLE_ra_dec_data[:,0]), max(OGLE_ra_dec_data[:,0]),
    min(OGLE_ra_dec_data[:,1]), max(OGLE_ra_dec_data[:,1]))

#----------------------------------------------------

# 24334 lensing events in OGLE catalog
#  Find min, max values of (ra, dec):
# 2.3416 < ra < 279.6578  | -73.7461 < dec < 54.6622

#### Plotting

In [ ]:
#    PLOTTING

# Color points
# Mycolor_points = 'red'
Mycolor_points = 'black'

fig = plt.figure() 

plt.plot(OGLE_ra_dec_data[:,0], OGLE_ra_dec_data[:,1], 
        Mycolor_points, marker='.', ms=1, ls='None', alpha=0.3)

# plt.plot(ra_dec_sub_np[:-10,0], ra_dec_sub_np[:-10,1], 
#         Mycolor_points, marker='.', ms=1, ls='None', alpha=0.3)

plt.xlim(ra_max, ra_min)
plt.ylim(dec_min, dec_max)
#plt.gca().invert_xaxis() # Invert x-axis

plt.xlabel("RA")
plt.ylabel("DEC")
plt.title("OGLE lensing map (%s events)"%len(OGLE_ra_dec_data))

plt.savefig(DirSaveOutput+'Plot_OGLE_map.png'%(), dpi=100)

# plt.savefig(DirSaveOutput+'LSST_ra_%.0f_%.0f_dec_%.0f_%.0f_Jump_%s_Plot.png'%(
#     ra_min, ra_max, dec_min, dec_max, JumpsSubsample), dpi=100)

plt.close()

In [ ]:
plt.close();plt.close();plt.close()

### Measure the events in a grid

#### Main loop

In [ ]:
# Initialize the timing of computation
now_start = datetime.datetime.now()
time_start = now_start.strftime("%Y-%m-%d (yyyy-mm-dd); %H:%M hrs.")
print "# Starting time of computing: %s"%time_start

In [ ]:
#       Main loop

#------------------------------------
# Create text file:
textfile_1 = open(DirSaveOutput+'Table_OGLE_events_sq2.dat', 'w')

textfile_1.write("#      Number of EVENTS in the OGLE catalogue \n# \n")

textfile_1.write("# Region in the sky: %s < ra < %s, %s < dec < %s \n"%(
ra_min, ra_max, dec_min, dec_max))

now = datetime.datetime.now() # Read the time and date right now
text_timenow = now.strftime("%Y-%m-%d (yyyy-mm-dd); %H:%M hrs.")
text_Date   = '# On date: %s \n'%text_timenow
text_Author = '# Data table created by: Arturo Avelino \n'
text_script = '# Script used: %s \n'%NotebookName
text_line = '#'+'-'*45 + '\n'

textfile_1.write(text_line); 
textfile_1.write(text_Author); textfile_1.write(text_Date); 
textfile_1.write(text_script);
textfile_1.write(text_line); 

textfile_1.write("# ra       dec    Num events \n")

text_line_short = '#'+'-'*10 + '\n'
#------------------------------------
# Reset:
count_ra_dec_int = 0;
count_iterations = 0;

# Loop over 'dec'
for i3 in range(int(dec_min), int(dec_max)):  
    
    dec_min_int = i3
    dec_max_int = dec_min_int + 1
        
    # Loop over 'ra'
    for i2 in range(int(ra_min), int(ra_max)):
        
        ra_min_int = i2;
        ra_max_int = ra_min_int + 1
        
        count_ra_dec_int = 0;

        for i1 in range(len(OGLE_ra_dec_data)):

            ra_int =  OGLE_ra_dec_data[i1][0]
            dec_int = OGLE_ra_dec_data[i1][1]
            
            # Count total number of iterations:
            count_iterations += 1

            if (ra_int > ra_min_int and ra_int < ra_max_int and
                dec_int>dec_min_int and dec_int<dec_max_int):
                
                count_ra_dec_int += 1 
        #----------       
        text_10 = "%s %s  %s %s  %s \n"%(
            ra_min_int, ra_max_int,
            dec_min_int, dec_max_int,
            count_ra_dec_int)
        textfile_1.write(text_10)
        # print "%s %s :%5s #"%(ra_min_int,ra_max_int,count_ra_int)
        
    # Write a line to better visualize the table
    textfile_1.write(text_line_short)

#--------------------------- 

text_15 = "# %s = total number of iteration in the whole loop.\n"%count_iterations
textfile_1.write(text_15)
print text_15

textfile_1.close()

In [ ]:
textfile_1.close();textfile_1.close();textfile_1.close()

In [ ]:
print "#     Time Summary "
print "# Starting time of computing: %s"%time_start
#----------------------
now_end = datetime.datetime.now()
time_end = now_end.strftime("%Y-%m-%d (yyyy-mm-dd); %H:%M hrs.")
print "# Ending time of computing: %s"%time_end
#----------------------
# Compute the time the  computations took:
time_compute = now_end - now_start
print "# Total time of computing:  %s"%time_compute
print "# %s = total number of iteration in the whole loop."%count_iterations
print "#---------------------------"

In [ ]:
#     Time Summary 
# Starting time of computing: 2018-07-12 (yyyy-mm-dd); 15:57 hrs.
# Ending time of computing: 2018-07-12 (yyyy-mm-dd); 15:58 hrs.
# Total time of computing:  0:00:42.132605
# 20075550 = total number of iteration in the whole loop.
#---------------------------

----

# Section 2
# LSST catalog: Number of events per square degree

In [ ]:
# Read LSST data file

# LSST_sample_file = 'LSST_ra_250_283_dec_-40_-15_Jump_100_RA_DEC.dat'
LSST_sample_file = 'LSST_ra_250_283_dec_-40_-15_RA_DEC.dat'

DirLSSTStarSubsample = '/Users/arturo/Documents/Research/LSST/Catalog/Subsamples/'

LSST_ra_dec_data = np.genfromtxt(DirLSSTStarSubsample+LSST_sample_file)

In [ ]:
"""
array([[ 268.0293,  -20.1814],
       [ 267.9925,  -20.1728],
       [ 268.0232,  -20.1975],
       [ 267.9061,  -20.1529],
       [ 267.9213,  -20.1995]])  """

LSST_ra_dec_data[:5]

#### Main loop

In [ ]:
# Initialize the timing of computation
now_start = datetime.datetime.now()
time_start = now_start.strftime("%Y-%m-%d (yyyy-mm-dd); %H:%M hrs.")
print "# Starting time of computing: %s"%time_start

In [ ]:
#       Main loop

#------------------------------------
# Create text file:
textfile_1 = open(DirSaveOutput+'Table_LSST_stars_sq2.dat', 'w')

textfile_1.write("#      Number of STARS in the LSST catalogue \n# \n")

textfile_1.write("# LSST file: '%s' \n"%(LSST_sample_file))
textfile_1.write("# %s \n"%(DirLSSTStarSubsample))
textfile_1.write("# \n")

textfile_1.write("# Region in the sky: %s < ra < %s, %s < dec < %s \n"%(
ra_min, ra_max, dec_min, dec_max))

now = datetime.datetime.now() # Read the time and date right now
text_timenow = now.strftime("%Y-%m-%d (yyyy-mm-dd); %H:%M hrs.")
text_Date   = '# On date: %s \n'%text_timenow
text_Author = '# Data table created by: Arturo Avelino \n'
text_script = '# Script used: %s \n'%NotebookName
text_line = '#'+'-'*45 + '\n'

textfile_1.write(text_line); 
textfile_1.write(text_Author); textfile_1.write(text_Date); 
textfile_1.write(text_script);
textfile_1.write(text_line); 

textfile_1.write("# ra       dec    Num stars \n")

text_line_short = '#'+'-'*10 + '\n'
#------------------------------------
# Reset:
count_ra_dec_int = 0;
count_iterations = 0;

# Loop over 'dec'
for i3 in range(int(dec_min), int(dec_max)):  
    
    dec_min_int = i3
    dec_max_int = dec_min_int + 1
        
    # Loop over 'ra'
    for i2 in range(int(ra_min), int(ra_max)):
        
        ra_min_int = i2;
        ra_max_int = ra_min_int + 1
        
        count_ra_dec_int = 0;

        for i1 in range(len(LSST_ra_dec_data)):

            ra_int =  LSST_ra_dec_data[i1][0]
            dec_int = LSST_ra_dec_data[i1][1]
            
            # Count total number of iterations:
            count_iterations += 1

            if (ra_int > ra_min_int and ra_int < ra_max_int and
                dec_int>dec_min_int and dec_int<dec_max_int):
                
                count_ra_dec_int += 1 
        #----------       
        text_10 = "%s %s  %s %s  %s \n"%(
            ra_min_int, ra_max_int,
            dec_min_int, dec_max_int,
            count_ra_dec_int)
        textfile_1.write(text_10)
        # print "%s %s :%5s #"%(ra_min_int,ra_max_int,count_ra_int)
        
    # Write a line to better visualize the table
    textfile_1.write(text_line_short)

#--------------------------- 

text_15 = "# %s = total number of iteration in the whole loop.\n"%count_iterations
textfile_1.write(text_15)
print text_15

#---------------------------
# Write timing

text_16 = "#     Time Summary \n"
text_17 = "# Starting time of computing: %s \n"%time_start

textfile_1.write("# \n")
now_end = datetime.datetime.now()
time_end = now_end.strftime("%Y-%m-%d (yyyy-mm-dd); %H:%M hrs.")
text_18 = "# Ending time of computing: %s \n"%time_end

# Compute the time the  computations took:
time_compute = now_end - now_start
text_19 = "# Total time of computing:  %s \n"%time_compute

textfile_1.write(text_16);textfile_1.write(text_17);
textfile_1.write(text_18);textfile_1.write(text_19);

#---------------------------
textfile_1.close()

print text_16,text_17, text_18, text_19

In [ ]:
textfile_1.close();textfile_1.close();textfile_1.close()

----

# Section 3
# Number of stars - events per square degree: LSST - OGLE catalogs

In [23]:
# Read OGLE data table

LSST_stars_sq2_file = 'Table_LSST_stars_sq2_.dat'
DirLSSTStarSubsample = '/Users/arturo/Dropbox/Research/Articulos/14_PLASTICC/OGLE/Plots/'

LSST_ra_dec_data = np.genfromtxt(DirLSSTStarSubsample+LSST_stars_sq2_file, 
                                 dtype=[int,int,int,int,int])

#----------------------------------
# Read OGLE data table

OGLE_events_sq2_file = 'Table_OGLE_events_sq2_.dat'
Dir_OGLE_file = '/Users/arturo/Dropbox/Research/Articulos/14_PLASTICC/OGLE/Plots/'

OGLE_ra_dec_data = np.genfromtxt(Dir_OGLE_file+OGLE_events_sq2_file, 
                                 dtype=[int,int,int,int,int])

Main loop

In [24]:
#       Main loop

#------------------------------------
# Create text file:
textfile_1 = open(DirSaveOutput+'Table_LSST_OGLE_sq2.dat', 'w')

textfile_1.write("#      Number of STARS  in the LSST catalogue \n")
textfile_1.write("#      Number of EVENTS in the OGLE catalogue \n# \n")

textfile_1.write("# LSST file: '%s' \n"%(LSST_stars_sq2_file))
textfile_1.write("# %s \n"%(DirLSSTStarSubsample))
textfile_1.write("# OGLE file: '%s' \n"%(OGLE_events_sq2_file))
textfile_1.write("# %s \n"%(Dir_OGLE_file))
textfile_1.write("# \n")

textfile_1.write("# Region in the sky: %s < ra < %s, %s < dec < %s \n"%(
ra_min, ra_max, dec_min, dec_max))

now = datetime.datetime.now() # Read the time and date right now
text_timenow = now.strftime("%Y-%m-%d (yyyy-mm-dd); %H:%M hrs.")
text_Date   = '# On date: %s \n'%text_timenow
text_Author = '# Data table created by: Arturo Avelino \n'
text_script = '# Script used: %s \n'%NotebookName
text_line = '#'+'-'*45 + '\n'

textfile_1.write(text_line); 
textfile_1.write(text_Author); textfile_1.write(text_Date); 
textfile_1.write(text_script);
textfile_1.write(text_line); 

textfile_1.write("# ra       dec    #stars #events \n")

text_line_short = '#'+'-'*10 + '\n'
#------------------------------------

count_stars = 0;
count_events = 0;

for i in range(len(LSST_ra_dec_data)):
    
    num_stars =  LSST_ra_dec_data[i][4]
    num_events = OGLE_ra_dec_data[i][4]
    
    # Count number of stars
    count_stars = count_stars + num_stars
    # Count number of events
    count_events = count_events + num_events
    
    textfile_1.write("%s %s %s %s   %-5s %s \n"%(
        LSST_ra_dec_data[i][0], LSST_ra_dec_data[i][1],
        LSST_ra_dec_data[i][2], LSST_ra_dec_data[i][3],
        num_stars, num_events
        ))
    
#--------------------------- 

text_15 = "# %s = total number of stars.\n"%count_stars
text_16 = "# %s = total number of events.\n"%count_events

textfile_1.write(text_line); 
textfile_1.write(text_15); textfile_1.write(text_16)
print text_15, text_16

textfile_1.close()

# 6046603 = total number of stars.
# 24259 = total number of events.



In [25]:
textfile_1.close();textfile_1.close();textfile_1.close();

#### Plot stars vs events

In [28]:
filename_1 = 'Table_LSST_OGLE_sq2.dat'
Dir_filename_1 = '/Users/arturo/Dropbox/Research/Articulos/14_PLASTICC/OGLE/Plots/'

LSST_OGLE_data = np.genfromtxt(Dir_filename_1+filename_1)

In [29]:
"""
array([[   250.,    251.,    -40.,    -39.,   6703.,      0.],
       [   251.,    252.,    -40.,    -39.,  10632.,      0.],
       [   252.,    253.,    -40.,    -39.,  12104.,      0.],
       [   253.,    254.,    -40.,    -39.,  12461.,      0.],
       [   254.,    255.,    -40.,    -39.,   7414.,      0.]]) """

LSST_OGLE_data[:5]

array([[   250.,    251.,    -40.,    -39.,   6703.,      0.],
       [   251.,    252.,    -40.,    -39.,  10632.,      0.],
       [   252.,    253.,    -40.,    -39.,  12104.,      0.],
       [   253.,    254.,    -40.,    -39.,  12461.,      0.],
       [   254.,    255.,    -40.,    -39.,   7414.,      0.]])

In [32]:
# Plot

UseLogScale = False

#      Color points
# Mycolor_points = 'red'
# Mycolor_points = 'black'
Mycolor_points = 'blue'

#--------------------------
fig = plt.figure() 

for i in range(len(LSST_OGLE_data)):
    
    stars_int = LSST_OGLE_data[i,4]
    event_int = LSST_OGLE_data[i,5] 
    
    if event_int> 0:
        # print stars_int, event_int
        plt.plot(stars_int, event_int, 
        Mycolor_points, marker='.', ms=10, ls='None', alpha=0.3)


if UseLogScale: plt.yscale('log')

plt.xlabel("Stars (LSST)")
plt.ylabel("Events (OGLE)")


plt.title("LSST vs OGLE (%s data)"%len(LSST_OGLE_data))

if UseLogScale: append_1 = '_log'
else: append_1 = ''
plt.savefig(DirSaveOutput+'Table_LSST_OGLE_sq2_Plot%s_.png'%(append_1), dpi=150)

plt.close()

In [33]:
plt.close();plt.close();plt.close();plt.close();