# Number of events per square degree in OGLE and LSST catalogs

### User

In [1]:
# USER

## Patch of the sky in the Milky way observed by OGLE:
# ra_min = 250.0; ra_max = 283.0;
# dec_min = -40.0; dec_max = -15.0;

# ok
# ra_min = 268.0; ra_max = 272.0;
# dec_min = -31.0; dec_max = -28.5;

# ok
# ra_min = 268.0; ra_max = 270.0;
# dec_min = -32.5; dec_max = -28.5;

# ok
# ra_min = 269.5; ra_max = 272.5;
# dec_min = -30.5; dec_max = -27.5;

# ok
# ra_min = 270.0; ra_max = 272.5;
# dec_min = -30.0; dec_max = -27.0;

#-----------------
# right side

# ok
# ra_min = 264.5; ra_max = 267.5;
# dec_min = -24.0; dec_max = -22.0;


ra_min = 262.0; ra_max = 264.0;
dec_min = -30.0; dec_max = -28.0;

#-------------------------------

# Size of the square subdivision of the area defined by (ra,dec)
# to determine the number of events and stars within.

Size_subdivision = 0.5  # degrees

#-------------------------------

DirSaveOutput = '/Users/arturo/Dropbox/Research/Articulos/\
14_PLASTICC/OGLE/Region_ra_%s_%s_dec_%s_%s_size_%s/'%(
ra_min, ra_max, dec_min, dec_max,Size_subdivision)

#-------------------------------
# Given that javascript doesn't work in JupyterLab, I have to set the 
# name of the notebook by hand
NotebookName = 'OGLE_LSST__data_per_sq_degree.ipynb'

### Automatic

In [2]:
import numpy as np
# import pandas as pd
import os # To use command line like instructions
import glob # To read the files in my directory
from matplotlib import pyplot as plt

5+4

9

In [3]:
#- Force the creation of the directory to save the outputs.
#- "If the subdirectory does not exist then create it"
import os # To use command line like instructions
if not os.path.exists(DirSaveOutput): os.makedirs(DirSaveOutput)

In [4]:
# Get the current date and time
import datetime 

# Read the time and date now
now = datetime.datetime.now()
print now

2018-07-15 16:33:46.272068


In [5]:
## Patch of the sky in the Milky way observed by OGLE:
ra_min_ogle_fix = 250.0; ra_max_ogle_fix = 283.0;
dec_min_ogle_fix = -40.0; dec_max_ogle_fix = -15.0;

------------

# Section 1
# OGLE: Count the number of events per square degree

In [6]:
# Read OGLE data table

OGLE_file = 'tl.txt'
Dir_OGLE_file = '/Users/arturo/Documents/Research/LSST/OGLE/'

OGLE_ra_dec_data = np.genfromtxt(Dir_OGLE_file+OGLE_file, usecols=[9,10])

In [7]:
"""
array([[ 271.0843875 ,  -27.41257778],
       [ 271.08435833,  -27.41314444],
       [ 271.22726667,  -27.43056111],
       [ 271.22724583,  -27.4305    ],
       [ 271.41127917,  -27.14167778]])
"""

OGLE_ra_dec_data[:5]

array([[271.0843875 , -27.41257778],
       [271.08435833, -27.41314444],
       [271.22726667, -27.43056111],
       [271.22724583, -27.4305    ],
       [271.41127917, -27.14167778]])

In [8]:
print "# %s"%OGLE_ra_dec_data[0]
print "# %s"%OGLE_ra_dec_data[-1]

# [ 271.0843875   -27.41257778]
# [ 265.295125    -27.58233333]

# [271.0843875  -27.41257778]
# [265.295125   -27.58233333]


In [9]:
print "# %s lensing events in OGLE catalog"%len(OGLE_ra_dec_data)
print "#  Find min, max values of (ra, dec):"
print "# %.4f < ra < %.4f  | %.4f < dec < %.4f"%(
    min(OGLE_ra_dec_data[:,0]), max(OGLE_ra_dec_data[:,0]),
    min(OGLE_ra_dec_data[:,1]), max(OGLE_ra_dec_data[:,1]))

#----------------------------------------------------

# 24334 lensing events in OGLE catalog
#  Find min, max values of (ra, dec):
# 2.3416 < ra < 279.65b78  | -73.7461 < dec < 54.6622

# 24334 lensing events in OGLE catalog
#  Find min, max values of (ra, dec):
# 2.3416 < ra < 279.6578  | -73.7461 < dec < 54.6622


#### Plotting the event map in the selected region of the sky

In [10]:
#    PLOTTING

# Color points
# Mycolor_points = 'red'
Mycolor_points = 'black'

fig = plt.figure() 

plt.plot(OGLE_ra_dec_data[:,0], OGLE_ra_dec_data[:,1], 
        Mycolor_points, marker='.', ms=1, ls='None', alpha=1)

# plt.plot(ra_dec_sub_np[:-10,0], ra_dec_sub_np[:-10,1], 
#         Mycolor_points, marker='.', ms=1, ls='None', alpha=0.3)

plt.xlim(ra_max, ra_min)
plt.ylim(dec_min, dec_max)
#plt.gca().invert_xaxis() # Invert x-axis
plt.grid(alpha=0.2, ls='--')

plt.xlabel("RA")
plt.ylabel("DEC")
plt.title("OGLE lensing map (%s events)"%len(OGLE_ra_dec_data))

plt.savefig(DirSaveOutput+'Plot_OGLE_map_.png', dpi=100)

# plt.savefig(DirSaveOutput+'LSST_ra_%.0f_%.0f_dec_%.0f_%.0f_Jump_%s_Plot.png'%(
#     ra_min, ra_max, dec_min, dec_max, JumpsSubsample), dpi=100)

plt.close()

In [11]:
plt.close();plt.close();plt.close();

#### Plot the region of the sky highlighted with a rectangle.

In [12]:
rectangle_coord = np.array([[ra_min, dec_min],
                [ra_min, dec_max],
                [ra_max, dec_max],
                [ra_max, dec_min],
                [ra_min, dec_min]])

In [13]:
#    PLOTTING

# Color points
# Mycolor_points = 'red'
Mycolor_points = 'black'

#-------------------------------

#-------------------------------

fig = plt.figure() 

plt.plot(OGLE_ra_dec_data[:,0], OGLE_ra_dec_data[:,1], 
        Mycolor_points, marker='.', ms=1, ls='None', alpha=0.5)

plt.plot(rectangle_coord[:,0], rectangle_coord[:,1], 
        color='red')

plt.xlim(ra_max_ogle_fix, ra_min_ogle_fix)
plt.ylim(dec_min_ogle_fix, dec_max_ogle_fix)
#plt.gca().invert_xaxis() # Invert x-axis
plt.grid(alpha=0.2, ls='--')

plt.xlabel("RA")
plt.ylabel("DEC")
plt.title("OGLE lensing map (%s events)"%len(OGLE_ra_dec_data))

plt.savefig(DirSaveOutput+'Plot_OGLE_map_all_.png', dpi=100)

# plt.savefig(DirSaveOutput+'LSST_ra_%.0f_%.0f_dec_%.0f_%.0f_Jump_%s_Plot.png'%(
#     ra_min, ra_max, dec_min, dec_max, JumpsSubsample), dpi=100)

plt.close()

In [14]:
plt.close();plt.close();plt.close();
plt.close();plt.close();plt.close();
plt.close();plt.close();plt.close();

### Count the number of events in a grid

#### Main loop

In [15]:
# Initialize the timing of computation
now_start = datetime.datetime.now()
time_start = now_start.strftime("%Y-%m-%d (yyyy-mm-dd); %H:%M hrs.")
print "# Starting time of computing: %s"%time_start

# Starting time of computing: 2018-07-15 (yyyy-mm-dd); 16:33 hrs.


In [16]:
#       Main loop

#------------------------------------
# Create text file:
textfile_1 = open(DirSaveOutput+'Table_OGLE_events_sq_.dat', 'w')

textfile_1.write("#      Number of EVENTS in the OGLE catalogue \n# \n")

textfile_1.write("# Region in the sky: %s < ra < %s, %s < dec < %s \n"%(
ra_min, ra_max, dec_min, dec_max))

now = datetime.datetime.now() # Read the time and date right now
text_timenow = now.strftime("%Y-%m-%d (yyyy-mm-dd); %H:%M hrs.")
text_Date   = '# On date: %s \n'%text_timenow
text_Author = '# Data table created by: Arturo Avelino \n'
text_script = '# Script used: %s \n'%NotebookName
text_line = '#'+'-'*45 + '\n'

textfile_1.write(text_line); 
textfile_1.write(text_Author); textfile_1.write(text_Date); 
textfile_1.write(text_script);
textfile_1.write(text_line); 

textfile_1.write("# ra_min ra_max  dec_min dec_max   # events \n")

text_line_short = '#'+'-'*10 + '\n'
#------------------------------------
# Reset:
count_ra_dec_int = 0;
count_iterations = 0;


range_ra = int(float(ra_max - ra_min)/Size_subdivision)
range_dec = int(float(dec_max - dec_min)/Size_subdivision)

# Loop over 'dec'
for i3 in range(range_dec):
    
    dec_min_int = dec_min + float(i3)*Size_subdivision
    dec_max_int = dec_min_int + Size_subdivision
    # print "   dec = (%s, %s)"%(dec_min_int, dec_max_int);

    # Loop over 'ra'
    for i2 in range(range_ra):
        
        ra_min_int = ra_min + float(i2)*Size_subdivision;
        ra_max_int = ra_min_int + Size_subdivision
        # print "ra = (%s, %s)"%(ra_min_int, ra_max_int);
        
        count_ra_dec_int = 0;

        for i1 in range(len(OGLE_ra_dec_data)):

            ra_int =  OGLE_ra_dec_data[i1][0]
            dec_int = OGLE_ra_dec_data[i1][1]
            
            # Count total number of iterations:
            count_iterations += 1

            if (ra_int > ra_min_int and ra_int < ra_max_int and
                dec_int>dec_min_int and dec_int<dec_max_int):
                
                count_ra_dec_int += 1 
        #----------   
        text_10 = "%s    %s   %s   %s     %s \n"%(
            ra_min_int, ra_max_int,
            dec_min_int, dec_max_int,
            count_ra_dec_int)
        textfile_1.write(text_10)
        # print "%s %s :%5s #"%(ra_min_int,ra_max_int,count_ra_int)
        
    # Write a line to better visualize the table
    textfile_1.write(text_line_short)

#--------------------------- 

text_15 = "# %s = total number of iteration in the whole loop.\n"%count_iterations
textfile_1.write(text_15)
print text_15

#---------------------------
# Write timing

text_16 = "#     Time Summary \n"
text_17 = "# Starting time of computing: %s \n"%time_start

textfile_1.write("# \n")
now_end = datetime.datetime.now()
time_end = now_end.strftime("%Y-%m-%d (yyyy-mm-dd); %H:%M hrs.")
text_18 = "# Ending time of computing: %s \n"%time_end

# Compute the time the  computations took:
time_compute = now_end - now_start
text_19 = "# Total time of computing:  %s \n"%time_compute

textfile_1.write(text_16);textfile_1.write(text_17);
textfile_1.write(text_18);textfile_1.write(text_19);

#---------------------------
textfile_1.close()

print text_16,text_17, text_18, text_19

# 389344 = total number of iteration in the whole loop.

#     Time Summary 
# Starting time of computing: 2018-07-15 (yyyy-mm-dd); 16:33 hrs. 
# Ending time of computing: 2018-07-15 (yyyy-mm-dd); 16:33 hrs. 
# Total time of computing:  0:00:00.856681 



In [17]:
textfile_1.close();textfile_1.close();textfile_1.close()

In [18]:
print "#     Time Summary "
print "# Starting time of computing: %s"%time_start
#----------------------
now_end = datetime.datetime.now()
time_end = now_end.strftime("%Y-%m-%d (yyyy-mm-dd); %H:%M hrs.")
print "# Ending time of computing: %s"%time_end
#----------------------
# Compute the time the  computations took:
time_compute = now_end - now_start
print "# Total time of computing:  %s"%time_compute
print "# %s = total number of iteration in the whole loop."%count_iterations
print "#---------------------------"

#     Time Summary 
# Starting time of computing: 2018-07-15 (yyyy-mm-dd); 16:33 hrs.
# Ending time of computing: 2018-07-15 (yyyy-mm-dd); 16:33 hrs.
# Total time of computing:  0:00:00.903962
# 389344 = total number of iteration in the whole loop.
#---------------------------


In [19]:
#     Time Summary 
# Starting time of computing: 2018-07-12 (yyyy-mm-dd); 15:57 hrs.
# Ending time of computing: 2018-07-12 (yyyy-mm-dd); 15:58 hrs.
# Total time of computing:  0:00:42.132605
# 20075550 = total number of iteration in the whole loop.
#---------------------------

----

# Section 2
# LSST: Count the number of -stars- per square degree

In [20]:
# Read LSST data file

LSST_sample_file = 'LSST_ra_250_283_dec_-40_-15_Jump_100_RA_DEC.dat'
# LSST_sample_file = 'LSST_ra_250_283_dec_-40_-15_RA_DEC.dat'

DirLSSTStarSubsample = '/Users/arturo/Documents/Research/LSST/Catalog/Subsamples/'

LSST_ra_dec_data = np.genfromtxt(DirLSSTStarSubsample+LSST_sample_file)

In [21]:
"""
array([[ 268.0293,  -20.1814],
       [ 267.9925,  -20.1728],
       [ 268.0232,  -20.1975],
       [ 267.9061,  -20.1529],
       [ 267.9213,  -20.1995]])  """

LSST_ra_dec_data[:5]

array([[269.9092, -28.3269],
       [267.0524, -32.4916],
       [273.7256, -16.1384],
       [276.9095, -18.2496],
       [273.0041, -16.2747]])

### Count the number of stars in a grid

#### Main loop

In [22]:
# Initialize the timing of computation
now_start = datetime.datetime.now()
time_start = now_start.strftime("%Y-%m-%d (yyyy-mm-dd); %H:%M hrs.")
print "# Starting time of computing: %s"%time_start

# Starting time of computing: 2018-07-15 (yyyy-mm-dd); 16:33 hrs.


In [23]:
#       Main loop

#------------------------------------
# Create text file:
textfile_1 = open(DirSaveOutput+'Table_LSST_stars_sq_.dat', 'w')

textfile_1.write("#      Number of STARS in the LSST catalogue \n# \n")

textfile_1.write("# LSST file: '%s' \n"%(LSST_sample_file))
textfile_1.write("# %s \n"%(DirLSSTStarSubsample))
textfile_1.write("# \n")

textfile_1.write("# Region in the sky: %s < ra < %s, %s < dec < %s \n"%(
ra_min, ra_max, dec_min, dec_max))

now = datetime.datetime.now() # Read the time and date right now
text_timenow = now.strftime("%Y-%m-%d (yyyy-mm-dd); %H:%M hrs.")
text_Date   = '# On date: %s \n'%text_timenow
text_Author = '# Data table created by: Arturo Avelino \n'
text_script = '# Script used: %s \n'%NotebookName
text_line = '#'+'-'*45 + '\n'

textfile_1.write(text_line); 
textfile_1.write(text_Author); textfile_1.write(text_Date); 
textfile_1.write(text_script);
textfile_1.write(text_line); 

textfile_1.write("# ra_min ra_max  dec_min dec_max   # stars \n")

text_line_short = '#'+'-'*10 + '\n'

#------------------------------------

# Reset:
count_ra_dec_int = 0;
count_iterations = 0;

range_ra = int(float(ra_max - ra_min)/Size_subdivision)
range_dec = int(float(dec_max - dec_min)/Size_subdivision)

# Loop over 'dec'
# old. for i3 in range(int(dec_min), int(dec_max)):
for i3 in range(range_dec):
    
    # old. dec_min_int = i3
    # old. dec_max_int = dec_min_int + 1
    
    dec_min_int = dec_min + float(i3)*Size_subdivision
    dec_max_int = dec_min_int + Size_subdivision
    # print "   dec = (%s, %s)"%(dec_min_int, dec_max_int);
        
    # Loop over 'ra'
    # old. for i2 in range(int(ra_min), int(ra_max)):
    for i2 in range(range_ra):
        
        # ra_min_int = i2;
        # ra_max_int = ra_min_int + 1
        
        ra_min_int = ra_min + float(i2)*Size_subdivision;
        ra_max_int = ra_min_int + Size_subdivision
        # print "ra = (%s, %s)"%(ra_min_int, ra_max_int);
        
        count_ra_dec_int = 0;

        for i1 in range(len(LSST_ra_dec_data)):

            ra_int =  LSST_ra_dec_data[i1][0]
            dec_int = LSST_ra_dec_data[i1][1]
            
            # Count total number of iterations:
            count_iterations += 1

            if (ra_int > ra_min_int and ra_int < ra_max_int and
                dec_int>dec_min_int and dec_int<dec_max_int):
                
                count_ra_dec_int += 1 
        #----------       
        text_10 = "%s    %s   %s   %s     %s \n"%(
            ra_min_int, ra_max_int,
            dec_min_int, dec_max_int,
            count_ra_dec_int)
        textfile_1.write(text_10)
        # print "%s %s :%5s #"%(ra_min_int,ra_max_int,count_ra_int)
        
    # Write a line to better visualize the table
    textfile_1.write(text_line_short)

#--------------------------- 

text_15 = "# %s = total number of iteration in the whole loop.\n"%count_iterations
textfile_1.write(text_15)
print text_15

#---------------------------
# Write timing

text_16 = "#     Time Summary \n"
text_17 = "# Starting time of computing: %s \n"%time_start

textfile_1.write("# \n")
now_end = datetime.datetime.now()
time_end = now_end.strftime("%Y-%m-%d (yyyy-mm-dd); %H:%M hrs.")
text_18 = "# Ending time of computing: %s \n"%time_end

# Compute the time the  computations took:
time_compute = now_end - now_start
text_19 = "# Total time of computing:  %s \n"%time_compute

textfile_1.write(text_16);textfile_1.write(text_17);
textfile_1.write(text_18);textfile_1.write(text_19);

#---------------------------
textfile_1.close()

print text_16,text_17, text_18, text_19

# 967664 = total number of iteration in the whole loop.

#     Time Summary 
# Starting time of computing: 2018-07-15 (yyyy-mm-dd); 16:33 hrs. 
# Ending time of computing: 2018-07-15 (yyyy-mm-dd); 16:33 hrs. 
# Total time of computing:  0:00:01.749366 



In [24]:
textfile_1.close();textfile_1.close();textfile_1.close()

----

# Section 3
# Combine both tables created above: Number of stars - events per square degree: LSST - OGLE catalogs

In [25]:
# Read LSST data table

# LSST_stars_sq2_file = 'Table_LSST_stars_sq2_.dat'
LSST_stars_sq2_file = 'Table_LSST_stars_sq_.dat'

# DirLSSTStarSubsample = '/Users/arturo/Dropbox/Research/Articulos/14_PLASTICC/OGLE/Plots/'
DirLSSTStarSubsample = DirSaveOutput

LSST_ra_dec_data2 = np.genfromtxt(DirLSSTStarSubsample+LSST_stars_sq2_file, 
                                 dtype=[float,float,float,float,int])

#----------------------------------
# Read OGLE data table

# OGLE_events_sq2_file = 'Table_OGLE_events_sq2_.dat'
OGLE_events_sq2_file = 'Table_OGLE_events_sq_.dat'

# Dir_OGLE_file = '/Users/arturo/Dropbox/Research/Articulos/14_PLASTICC/OGLE/Plots/'
Dir_OGLE_file = DirSaveOutput

OGLE_ra_dec_data2 = np.genfromtxt(Dir_OGLE_file+OGLE_events_sq2_file, 
                                 dtype=[float,float,float,float,int])

Main loop

In [26]:
#       Main loop

#------------------------------------
# Create text file:
textfile_1 = open(DirSaveOutput+'Table_LSST_OGLE_sq_.dat', 'w')

textfile_1.write("#      Number of STARS  in the LSST catalogue \n")
textfile_1.write("#      Number of EVENTS in the OGLE catalogue \n# \n")

textfile_1.write("# LSST file: '%s' \n"%(LSST_stars_sq2_file))
textfile_1.write("# %s \n"%(DirLSSTStarSubsample))
textfile_1.write("# OGLE file: '%s' \n"%(OGLE_events_sq2_file))
textfile_1.write("# %s \n"%(Dir_OGLE_file))
textfile_1.write("# \n")

textfile_1.write("# Region in the sky: %s < ra < %s, %s < dec < %s \n"%(
ra_min, ra_max, dec_min, dec_max))

now = datetime.datetime.now() # Read the time and date right now
text_timenow = now.strftime("%Y-%m-%d (yyyy-mm-dd); %H:%M hrs.")
text_Date   = '# On date: %s \n'%text_timenow
text_Author = '# Data table created by: Arturo Avelino \n'
text_script = '# Script used: %s \n'%NotebookName
text_line = '#'+'-'*45 + '\n'

textfile_1.write(text_line); 
textfile_1.write(text_Author); textfile_1.write(text_Date); 
textfile_1.write(text_script);
textfile_1.write(text_line); 

# textfile_1.write("# ra       dec    #stars #events \n")
textfile_1.write("# ra_min ra_max  dec_min dec_max   # stars \n")

text_line_short = '#'+'-'*10 + '\n'
#------------------------------------

count_stars = 0;
count_events = 0;

for i in range(len(LSST_ra_dec_data2)):
    
    num_stars =  LSST_ra_dec_data2[i][4]
    num_events = OGLE_ra_dec_data2[i][4]
    
    # Count number of stars
    count_stars = count_stars + num_stars
    # Count number of events
    count_events = count_events + num_events
    
    textfile_1.write("%s %s %s %s   %-5s %s \n"%(
        LSST_ra_dec_data2[i][0], LSST_ra_dec_data2[i][1],
        LSST_ra_dec_data2[i][2], LSST_ra_dec_data2[i][3],
        num_stars, num_events
        ))
    
#--------------------------- 

text_15 = "# %s = total number of stars.\n"%count_stars
text_16 = "# %s = total number of events.\n"%count_events

textfile_1.write(text_line); 
textfile_1.write(text_15); textfile_1.write(text_16)
print text_15, text_16

textfile_1.close()

# 830 = total number of stars.
# 357 = total number of events.



In [27]:
textfile_1.close();textfile_1.close();textfile_1.close();

## Fit and Plot stars vs events

In [114]:
filename_1 = 'Table_LSST_OGLE_sq_.dat'

# ORIGINAL:
# Dir_filename_1 = DirSaveOutput  

# TEMPORAL:
Dir_filename_1 = '/Users/arturo/Dropbox/Research/Articulos/14_PLASTICC/OGLE/Plots_combiningData_rightSide/'
# Dir_filename_1 = '/Users/arturo/Dropbox/Research/Articulos/14_PLASTICC/OGLE/Plots_combiningData_all/'
DirSaveOutput = Dir_filename_1 

#----------------

LSST_OGLE_data = np.genfromtxt(Dir_filename_1+filename_1)

In [115]:
"""
array([[   250.,    251.,    -40.,    -39.,   6703.,      0.],
       [   251.,    252.,    -40.,    -39.,  10632.,      0.],
       [   252.,    253.,    -40.,    -39.,  12104.,      0.],
       [   253.,    254.,    -40.,    -39.,  12461.,      0.],
       [   254.,    255.,    -40.,    -39.,   7414.,      0.]]) """

LSST_OGLE_data[:5]

array([[262. , 262.5, -30. , -29.5,  45. ,  20. ],
       [262.5, 263. , -30. , -29.5,  55. ,  27. ],
       [263. , 263.5, -30. , -29.5,  51. ,  24. ],
       [263.5, 264. , -30. , -29.5,  58. ,  32. ],
       [262. , 262.5, -29.5, -29. ,  49. ,  23. ]])

#### Fit a line

In [116]:
best_fit = np.polyfit(LSST_OGLE_data[:,4], LSST_OGLE_data[:,5], 1)
print "# Best fit: slope = %.4f | intercept = %.4f"%(best_fit[0], best_fit[1])

# Best fit: slope = 0.4471 | intercept = -4.2076


In [117]:
# Best fit: slope = 0.4471 | intercept = -4.2076

#### Plot

In [118]:
#---------------------

# Line equation function
def line_eq(x, mm, bb):
    return  x*mm + bb

print "# test: %s"%(line_eq(10, slope_1, intercept_1))

#---------------------
# Define the  points of the fitted line in order to plot it.

slope_1 = best_fit[0]
intercept_1 = best_fit[1]

nbins1= 51
line_x = np.linspace(0, 200, nbins1) 
line_y = line_eq(line_x, slope_1, intercept_1)

# test 0.2635597264195999

# test: -91.5594909348228


In [119]:
#     Plot

#      Color points
# Mycolor_points = 'red'
# Mycolor_points = 'black'
Mycolor_points = 'blue'

# Use log scale (list):
UseLogScale_list = [False, True]

# Plot the best fitted line (list)
PlotBestFitLine_list = [False, True]

# Loop over plot the best fitted line:
for PlotBestFitLine in PlotBestFitLine_list:

    # Loop over log and linear plots:
    for UseLogScale in UseLogScale_list:

        # UseLogScale = verdad
        #--------------------------
        fig = plt.figure() 

        for i in range(len(LSST_OGLE_data)):

            stars_int = LSST_OGLE_data[i,4]
            event_int = LSST_OGLE_data[i,5] 

            # Make sure to plot areas with lensing events:
            if event_int > 0:
                # print stars_int, event_int
                plt.plot(stars_int, event_int, 
                Mycolor_points, marker='.', ms=10, ls='None', alpha=0.8)

        #-------------------
        # Plot the best fitted line
        if PlotBestFitLine:
            plt.plot(line_x,line_y, color = 'red', lw=2,
                    label="y = %.2f * x + (%.2f)"%(slope_1,intercept_1))
            plt.legend(loc='lower right')

        plt.grid(alpha=0.2, ls='--')

        if UseLogScale: plt.yscale('log')

        plt.xlim((min(LSST_OGLE_data[:,4])-2), (max(LSST_OGLE_data[:,4])+2))
        plt.ylim((min(LSST_OGLE_data[:,5])-2), (max(LSST_OGLE_data[:,5])+2))
        
        plt.xlabel("Stars (LSST)")
        plt.ylabel("Events (OGLE)")

        plt.title("LSST vs OGLE (%s data)"%len(LSST_OGLE_data))

        #-------------------
        
        if UseLogScale: append_1 = '_log'
        else: append_1 = ''
            
        if PlotBestFitLine: append_2 = '_bestFit'
        else: append_2 = ''
        
        plt.savefig(DirSaveOutput+'Table_LSST_OGLE_sq_Plot%s%s_.png'%(
            append_1,append_2), dpi=100)

        plt.close()

In [120]:
plt.close();plt.close();plt.close();plt.close();

In [121]:
print "# All done."

# All done.
